#!/usr/bin/env bash

describe_identical_files () {
	local f1="$1"
	local f2="$2"
	local full="$3"
	local escape="$4"
	if [ "x$escape" = "x1" ] ; then
		f1="$(printf '%q' "$f1")"
		f2="$(printf '%q' "$f2")"
	fi
	if [ "x$full" != "x1" ] && [ "x$(dirname "$f1")" = "x$(dirname "$f2")" ] ; then
		echo "$(dirname "$f1"): $(basename "$f1") and $(basename "$f2") are identical"
	else
		echo "$f1 and $f2 are identical"
	fi
}

full=0
escape=0
while (($# > 0)) ; do
	case "$1" in
		--full)
			full=1
			;;
		--escape)
			escape=1
			;;
		--)
			break
			;;
		*)
			break
			;;
	esac
	shift
done

dir="$1"
if [ "x$dir" = "x" ] ; then
	dir=.
fi

# adapted from: https://stackoverflow.com/a/8214748/2407870
# Note: the second "-not -path ." appears to be necessary if the target directory is "."
files=()
while IFS= read -d $'\0' -r f ; do
	files+=("$f")
done < <(find "$dir" -type f -not -path '*/\.*' -not -path . -print0)

# find identical files
i=0
identical_count=0
while ((i < ${#files[@]})) ; do
	if ! [ -e "${files[$i]}" ] ; then
		continue
	fi
	j=$(($i + 1))
	while ((j < ${#files[@]})) ; do
		if ! [ -e "${files[$j]}" ] ; then
			continue
		fi
		f1="${files[$i]}"
		f2="${files[$j]}"
		if diff -q "$f1" "$f2" > /dev/null 2>&1 ; then
			identical_count=$((identical_count + 1))
			describe_identical_files "$f1" "$f2" "$full" "$escape"
		fi
		j=$(($j + 1))
	done
	i=$(($i + 1))
done

# summarize
if ((identical_count > 0)) ; then
	echo "Found $identical_count pairs of identical files"
else
	echo "No identical files found"
fi
